### ISSUE TITLE
Kanban Board - Full Stack Group Project

### ISSUE THREAD

**Issue by anita00001** [anita00001/fix-mate-backend#18]
## Collaborator (Group of 4 people)
@anita00001 
@Mofuhidy 
@Theodoraldo 
@AnsarIbrahim 

## Link to issue link (Frontend)
https://github.com/anita00001/fix-mate-frontend/issues

# Link to the Project
https://github.com/users/anita00001/projects/5

## Screenshot of the Kanban Board
![image](https://github.com/anita00001/fix-mate-backend/assets/24216198/6af22972-9982-4560-ba4d-c943ffeb9330)

**Comment by anita00001** [comment]
## Screenshot of the Kanban Board
![image](https://github.com/anita00001/fix-mate-backend/assets/24216198/42ba8603-2bae-4eab-a753-5ad69d8b258f)

**Comment by Meltrust** [comment]
Hi @anita00001 ,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- All cards have descriptions, assignees and pointings according to spec ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
